name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install and build yarn
        run: |
          yarn
          yarn build
        working-directory: ./fontend
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0"
      - name: Build
        run: dotnet build ./api
      - name: Test
        run: dotnet test ./api/MyApp.Tests
